apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: azdevopstest.azurecr.io/workerapp:81
        name: worker
      imagePullSecrets:
      - name: acr-access  
